// DO NOT EDIT. This file is generated by fresh.
// This file SHOULD be checked into source version control.
// This file is automatically updated during development when running `dev.ts`.

import config from "./deno.json" assert { type: "json" };
import * as $0 from "./routes/[mindmap].tsx";
import * as $1 from "./routes/api/dbService.ts";
import * as $2 from "./routes/index.tsx";
import * as $$0 from "./islands/MindmapIsland.tsx";
import * as $$1 from "./islands/Textbox.tsx";
import * as $$2 from "./islands/TutorialVideo.tsx";

const manifest = {
  routes: {
    "./routes/[mindmap].tsx": $0,
    "./routes/api/dbService.ts": $1,
    "./routes/index.tsx": $2,
  },
  islands: {
    "./islands/MindmapIsland.tsx": $$0,
    "./islands/Textbox.tsx": $$1,
    "./islands/TutorialVideo.tsx": $$2,
  },
  baseUrl: import.meta.url,
  config,
};

export default manifest;
